Models/TodoTask.cs
using System.ComponentModel.DataAnnotations;

namespace TodoList.Models
{
    public class TodoTask
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        [Display(Name = "Created")]
        public DateTime CreatedDate { get; set; } = DateTime.Now;
        [Display(Name = "Updated")]
        public DateTime UpdatedDate { get; set; } = DateTime.Now;
        [Display(Name = "Due Date")]
        public DateTime DueDate { get; set; }
        public bool Finished { get; set; } = false;
        public User User { get; set; }
        public string UserId { get; set; }
        public IList<Tag>? Tags { get; set; }
        public TodoTaskList? TodoTaskList { get; set; }
        public int? TodoTaskListId { get; set; }

        public TodoTask()
        {
        }

        public TodoTask(int id, string title, string description, string userId)
        {
            Id = id;
            UserId = userId;
            Title = title;
            Description = description;
        }

        public TodoTask(int id, string title, string description, string userId, IList<Tag>? tags, TodoTaskList? todoTaskList, int? todoTaskListId) : this(id, title, description, userId)
        {
            Tags = tags;
            TodoTaskList = todoTaskList;
            TodoTaskListId = todoTaskListId;
        }
    }
}

Controllers/TodoTaskController.cs
using Microsoft.AspNetCore.Mvc;
using TodoList.Models;
using TodoList.Models.ViewModels;
using TodoList.Services;

namespace TodoList.Controllers
{
    public class TodoTaskController : Controller
    {
        private readonly TodoTaskService _todoTaskService;
        private readonly TodoTaskListService _todoTaskListService;
        private readonly UserService _userService;

        public TodoTaskController(TodoTaskService todoTaskService, TodoTaskListService todoTaskListService, UserService userService)
        {
            _todoTaskService = todoTaskService;
            _todoTaskListService = todoTaskListService;
            _userService = userService;
        }
        
        public async Task<IActionResult> TodoTaskInfo(int Id)
        {
            var todoTask = await _todoTaskService.GetTodoTaskAsync(Id);
            var viewModel = new EditTodoTaskViewModel {
                Id = todoTask.Id,
                Title = todoTask.Title,
                Description = todoTask.Description,
                DueDate = todoTask.DueDate,
                TodoTaskLists = await _todoTaskListService.GetTodoTaskListsAsync(User.Identity.Name),
                TodoTaskListId = todoTask.TodoTaskListId,
            };
            return View("_TodoTaskInfo", viewModel);
        }

        public async Task<IActionResult> TodoTaskListToday()
        {
            var tasks = await _todoTaskService.GetTodoTasksAsync(User.Identity.Name);
            return View("_TodoTaskListToday", tasks);
        }

        public async Task<IActionResult> TodoTaskListUpcoming()
        {
            var tasks = await _todoTaskService.GetTodoTasksAsync(User.Identity.Name);
            return View("_TodoTaskListUpcoming", tasks);
        }

        public async Task<IActionResult> Create()
        {
            var username = User.Identity.Name;
            var lists = await _todoTaskListService.GetTodoTaskListsAsync(username);
            var viewModel = new CreateTodoTaskViewModel() { TodoTaskLists = lists, DueDate = DateTime.Today};
            return View("_Create", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateTodoTaskViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var userId = await _userService.GetUserIdAsync(User.Identity.Name);
                var todoTask = new TodoTask();
                if (viewModel.TodoTaskListId != null)
                {
                    var todoTaskList = await _todoTaskListService.GetTodoTaskListAsync(User.Identity.Name, viewModel.TodoTaskListId);

                    todoTask.Title = viewModel.Title;
                    todoTask.Description = viewModel.Description;
                    todoTask.DueDate = viewModel.DueDate;
                    todoTask.UserId = userId;
                    todoTask.TodoTaskList = todoTaskList;
                    todoTask.TodoTaskListId = viewModel.TodoTaskListId;
                }
                else
                {
                    todoTask.Title = viewModel.Title;
                    todoTask.Description = viewModel.Description;
                    todoTask.DueDate = viewModel.DueDate;
                    todoTask.UserId = userId;
                }

                await _todoTaskService.CreateTodoTaskAsync(todoTask);
                return RedirectToAction("Index", "User");
            }
            return View("_Create", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(EditTodoTaskViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var todoTask = await _todoTaskService.GetTodoTaskAsync(viewModel.Id);
                if (todoTask != null)
                {
                    todoTask.Title = viewModel.Title;
                    todoTask.Description = viewModel.Description;
                    todoTask.DueDate= viewModel.DueDate;
                    todoTask.TodoTaskListId = viewModel.TodoTaskListId;

                    if (viewModel.TodoTaskListId != null)
                    {
                        todoTask.TodoTaskList = await _todoTaskListService.GetTodoTaskListAsync(User.Identity.Name, todoTask.TodoTaskListId);
                    }

                    await _todoTaskService.UpdateTodoTaskAsync(todoTask);
                    viewModel.TodoTaskLists = await _todoTaskListService.GetTodoTaskListsAsync(User.Identity.Name);

                    return RedirectToAction("Index", "User");
                }
            }
            return View("_TodoTaskInfo");
        }

        [HttpPut]
        public async Task<IActionResult> UpdateTodoTaskStatus(int id, bool finished)
        {
            var todoTask = await _todoTaskService.GetTodoTaskAsync(id);
            if (todoTask == null) 
            {
                return Json(new { Erro = "Erro:", Mensagem = "Usuário não encontrado" });
            }
            todoTask.Finished = finished;
            await _todoTaskService.UpdateTodoTaskAsync(todoTask);
            return Json(new { Sucesso = "Sucesso:", Mensagem = "Tarefa atualizada com sucesso" });
        }
    }
}

Views/TodoTask/_Create.cshtml
@model TodoList.Models.ViewModels.CreateTodoTaskViewModel

<div class="d-flex flex-column m-3 h-100">
    <h3>Tarefa</h3>
    <form asp-action="Create" asp-controller="TodoTask" method="post" class="d-flex flex-column justify-content-between h-100">
        <div class="">
            <div class="form-floating mb-3">
                <input asp-for="@Model.Title" type="text" class="form-control" />
                <label asp-for="@Model.Title">@Html.DisplayNameFor(model => model.Title)</label>
            </div>
            <div class="form-floating mb-3">
                <textarea asp-for="@Model.Description" class="form-control" style="height: 100px"></textarea>
                <label asp-for="@Model.Description">@Html.DisplayNameFor(model => model.Description)</label>
            </div>
            <div class="d-flex mb-3 align-items-center">
                <label class="fs-5 w-25">Lista</label>
                <select asp-for="@Model.TodoTaskListId" asp-items="@(new SelectList(Model.TodoTaskLists, "Id", "Title"))" class="form-control">
                    <option value=""></option>
                </select>
            </div>
            <div class="d-flex mb-3 align-items-center">
                <label class="fs-5 w-25">@Html.DisplayNameFor(model => model.DueDate)</label>
                <input type="datetime-local" asp-for="@Model.DueDate" class="form-control" />
            </div>
        </div>
        <div class="d-flex mb-5 justify-content-around">
            <a class="btn btn-secondary w-25 mx-2" id="closeForm">Cancelar</a>
            <button type="submit" class="btn btn-warning w-25">Criar tarefa</button>
        </div>
    </form>
</div>

<script src="/lib/jquery/dist/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $("#closeForm").on("click", function (e) {
            e.preventDefault();
            $("#part-3").empty();
        });
    });
</script>

Views/TodoTask/_TodoTaskInfo.cshtml
@model TodoList.Models.ViewModels.EditTodoTaskViewModel

<div class="d-flex flex-column m-3 h-100">
    <h3>Tarefa</h3>
    <form asp-action="Update" asp-controller="TodoTask" method="post" class="d-flex flex-column justify-content-between h-100">
        <div class="">
            <input type="hidden" asp-for="@Model.Id" />
            <div class="form-floating mb-3">
                <input asp-for="@Model.Title" type="text" class="form-control" />
                <label asp-for="@Model.Title">@Html.DisplayNameFor(model => model.Title)</label>
            </div>
            <div class="form-floating mb-3">
                <textarea asp-for="@Model.Description" class="form-control" style="height: 100px"></textarea>
                <label asp-for="@Model.Description">@Html.DisplayNameFor(model => model.Description)</label>
            </div>
            <div class="d-flex mb-3 align-items-center">
                <label class="fs-5 w-25">Lista</label>
                <select asp-for="@Model.TodoTaskListId" asp-items="@(new SelectList(Model.TodoTaskLists, "Id", "Title"))" class="form-control">
                    <option value=""></option>
                </select>
            </div>
            <div class="d-flex mb-3 align-items-center">
                <label class="fs-5 w-25">@Html.DisplayNameFor(model => model.DueDate)</label>
                <input type="datetime-local" asp-for="@Model.DueDate" class="form-control" />
            </div>
        </div>
        <div class="d-flex mb-5 justify-content-around">
            <a class="btn btn-secondary w-25 mx-2" id="closeForm">Cancelar</a>
            <button type="submit" class="btn btn-warning w-25">Atualizar tarefa</button>
        </div>
    </form>
</div>

<script src="/lib/jquery/dist/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $("#closeForm").on("click", function (e) {
            e.preventDefault();
            $("#part-3").empty();
        });
    });
</script>

Views/TodoTask/_TodoTaskListToday.cshtml
@model IList<TodoList.Models.TodoTask>

<h2 class="m-5">Hoje <span class="border ms-3 px-3 rounded">@Model.Where(t => t.DueDate.ToShortDateString() == DateTime.Today.ToShortDateString()).Count()</span></h2>

<div class="w-100 btn border p-3" id="createTodoTask">
    <span>
        +
    </span>
    <span>
        Adicionar nova tarefa
    </span>
</div>

@foreach (var todoTask in Model)
{
    if (todoTask.DueDate.ToShortDateString() == DateTime.Today.ToShortDateString())
    {
        <div class="d-flex justify-content-between mx-5">
            <div class="mt-3">
                <input asp-for="@todoTask.Finished" type="checkbox" class="todoTaskFinishedChk" value="@todoTask.Id" />
                <span class="mx-3">@todoTask.Title</span>
            </div>
            <div class="mt-3">
                <button class="btn todoTaskInfoBtn" data-id="@todoTask.Id">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z" />
                    </svg>
                </button>
            </div>
        </div>
    }   
}

<script src="/lib/jquery/dist/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $("#createTodoTask").on("click", function (e) {
            e.preventDefault();
            $.ajax({
                url: "/TodoTask/Create",
                method: "GET",
                success: function (data) {
                    $("#part-3").html(data);
                },
                error: function (error) {
                    console.error("Erro ao carregar a partial view: " + error);
                }
            });
        });

        $(".todoTaskInfoBtn").on("click", function (e) {
            e.preventDefault();
            const todoTaskId = $(this).data("id");
            $.ajax({
                url: "/TodoTask/TodoTaskInfo",
                method: "GET",
                data: { Id: todoTaskId },
                success: function (data) {
                    $("#part-3").html(data);
                },
                error: function (error) {
                    console.error("Erro ao carregar a partial view: " + error);
                }
            });
        });

        $(".todoTaskFinishedChk").change(function () {
            const id = $(this).val();
            const finished = $(this).is(":checked");

            $.ajax({
                url: "/TodoTask/UpdateTodoTaskStatus",
                type: "PUT",
                data: {
                    id: id,
                    finished: finished
                },
                success: function (data) {
                    alert(data.mensagem);
                },
                error: function (error) {
                    console.error(error);
                }
            });
        });
    });
</script>

Views/TodoTask/_TodoTaskListUpcoming.cshtml
@model IList<TodoList.Models.TodoTask>

<h2 class="m-5">Próximas <span class="border ms-3 px-3 rounded">@Model.Where(t => t.DueDate.ToShortDateString() != DateTime.Today.ToShortDateString()).Count()</span></h2>

<div class="w-100 btn border p-3" id="createTodoTask">
    <span>
        +
    </span>
    <span>
        Adicionar nova tarefa
    </span>
</div>

@foreach (var todoTask in Model)
{
    if (todoTask.DueDate.ToShortDateString() != DateTime.Today.ToShortDateString())
    {
        <div class="d-flex justify-content-between mx-5">
            <div class="mt-3">
                <input asp-for="@todoTask.Finished" type="checkbox" class="todoTaskFinishedChk" value="@todoTask.Id" />
                <span class="mx-3">@todoTask.Title</span>
            </div>
            <div class="mt-3">
                <button class="btn todoTaskInfoBtn" data-id="@todoTask.Id">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z" />
                    </svg>
                </button>
            </div>
        </div>
    }
}

<script src="/lib/jquery/dist/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $("#createTodoTask").on("click", function (e) {
            e.preventDefault();
            $.ajax({
                url: "/TodoTask/Create",
                method: "GET",
                success: function (data) {
                    $("#part-3").html(data);
                },
                error: function (error) {
                    console.error("Erro ao carregar a partial view: " + error);
                }
            });
        });

        $(".todoTaskInfoBtn").on("click", function (e) {
            e.preventDefault();
            const todoTaskId = $(this).data("id");
            $.ajax({
                url: "/TodoTask/TodoTaskInfo",
                method: "GET",
                data: { Id: todoTaskId },
                success: function (data) {
                    $("#part-3").html(data);
                },
                error: function (error) {
                    console.error("Erro ao carregar a partial view: " + error);
                }
            });
        });

        $(".todoTaskFinishedChk").change(function () {
            const id = $(this).val();
            const finished = $(this).is(":checked");

            $.ajax({
                url: "/TodoTask/UpdateTodoTaskStatus",
                type: "PUT",
                data: {
                    id: id,
                    finished: finished
                },
                success: function (data) {
                    alert(data.mensagem);
                },
                error: function (error) {
                    console.error(error);
                }
            });
        });
    });
</script>